name: Build zh_html

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'scripts/**'
      - '.gitignore'
      - '.github/**'
  schedule:
    - cron: '0 0 1 */3 *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  run-translation:
    runs-on: ubuntu-latest
    environment: prod
    env:
      LANGUAGE: Chinese
      BRANCH: zh_html

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: HackTricks-wiki/hacktricks
          ref: zh
          token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: 3.8

      # - name: Install python dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip3 install openai tqdm tiktoken

      - name: Cache Cargo registry and git index
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-primes

      # Install Rust and Cargo
      - name: Install Rust and Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      # Install mdBook and Plugins
      - name: Install mdBook and Plugins
        run: |
          cargo install mdbook &
          cargo install mdbook-alerts &
          cargo install mdbook-reading-time &
          cargo install mdbook-pagetoc &
          cargo install mdbook-tabs &
          cargo install mdbook-codename &
          wait

      # Build the mdBook
      - name: Build mdBook
        run: |
          echo '[book]' > book.toml
          echo 'src = "."' >> book.toml
          echo 'language = "zh"' >> book.toml
          mdbook build

      - name: ls Build File
        run: echo -e "\n目录内容如下:"; ls -la

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add lanyun https://github.com/$REPOSITORY.git
          git fetch lanyun $BRANCH --depth 1 || true
          git checkout -b "$BRANCH" FETCH_HEAD -f
          find . -maxdepth 1 -type f ! -name '.*' -exec rm -f {} +
          find . -maxdepth 1 -type d ! -name '.*' ! -name 'book' -exec rm -rf {} +
          mv ./book/* .
          rm -rf ./book
          git add .
          git commit -m "自动提交翻译html文件" || true
          git push --set-upstream lanyun "$BRANCH:$BRANCH" -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Save Cache
        id: cache-primes-save
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}

      